[[structure:Default]]
[role=group,includesConstraints="structure:ControllerDependencies,structure:ServiceDependencies,structure:RepositoryDependencies,structure:ImplementationDependencies,dependency:PackageCycles",includesConcepts="structure:PackageDependencies.graphml,structure:LayerDependencies.graphml"]
== Structural Rules And Reports

The following constraints are verified:

- <<structure:ControllerDependencies>>
- <<structure:ServiceDependencies>>
- <<structure:RepositoryDependencies>>
- <<structure:ImplementationDependencies>>
- Package cycles

The following GraphML reports are created:

- <<structure:LayerDependencies.graphml>>
- <<structure:PackageDependencies.graphml>>

=== Layers And Elements

The application consists of the following layers:

[plantuml,class-diagram]
....
package UI <<Frame>> {
  class MyController
}

package Logic <<Frame>> {
  interface MyService
  MyService <|-- MyServiceImpl
}

package Persistence <<Frame>> {
  interface FooRepository
  interface SpringDataFooRepository
  FooRepository <|-- SpringDataFooRepository
  FooRepository <|-- JpaFooRepositoryImpl
  FooRepository <|-- JdbcFooRepositoryImpl
}

MyController --> MyService : uses
MyServiceImpl --> FooRepository : uses

hide members
....

* UI
** Controller implementations
* Logic
** Service interfaces and implementations
* Persistence
** Repository interfaces and implementations
*** Spring Data (interface declaration only)
*** JPA
*** JDBC

=== Constraints

The following sections describe restrictions on dependencies between these layers.

==== General

[[structure:ImplementationDependencies]]
[source,cypher,role=constraint,requiresConcepts="spring-mvc:Controller,spring-mvc:Service,spring-data:Repository"]
.There must be no direct dependencies between Spring component implementations, i.e. only dependencies to interfaces are allowed.
----
MATCH
  (type:Spring:Component)-[:DECLARES]->(:Method)-[:INVOKES]->(:Method)<-[:DECLARES]-(otherType:Spring:Component)
WHERE
  type <> otherType
  and not otherType:Interface
RETURN DISTINCT
  type as Dependent, otherType as InvalidDependency
----


==== UI

The server side UI implementation is based on Spring MVC controllers:

[source,java]
.Example controller
----
@Controller
@RequestMapping("/resource")
public class MyController {

    private final MyService service;

    @Autowired
    public MyController(MyService myService) {
        this.myService = myService;
    }

    @RequestMapping(value = "/", method = RequestMethod.GET)
    public String get() {
    }
}
----

[[structure:ControllerDependencies]]
[source,cypher,role=constraint,requiresConcepts="structure:LayerDependencies"]
.A controller can only have dependencies to services (e.g. direct usage of repositories is not allowed).
----
MATCH
  (type:Spring:Controller)-[:USES]->(otherType:Spring:Component)
WHERE NOT
  otherType:Service
RETURN DISTINCT
  type as InvalidController, otherType as Dependency
----


==== Logic

The business logic consists of services which are defined by interfaces and implemented by classes annotated with @Service:

[source,java]
.Example service interface
----
public interface MyService {
    Collection<Foo> findFoos() throws DataAccessException;
}
----

[source,java]
.Example service implementation
----
@Service
public class MyServiceImpl implements MyService {

    private FooRepository fooRepository;

    @Autowired
    public ServiceImpl(FooRepository fooRepository) {
        this.fooRepository = fooRepository;
    }
}
----

[[structure:ServiceDependencies]]
[source,cypher,role=constraint,requiresConcepts="structure:LayerDependencies"]
.A service can only have dependencies to repositories or other services (e.g. usage of controllers is not allowed).
----
MATCH
  (type:Spring:Service)-[:USES]->(otherType:Spring:Component)
WHERE NOT (
  otherType:Service
  or otherType:Repository
)
RETURN DISTINCT
  type as InvalidService, otherType as Dependency
----


==== Persistence

Repositories provide access to the database and are defined by interfaces (one per model element):

[source,java]
.Example repository interface
----
public interface FooRepository {
    Collection<Foo> findFoos() throws DataAccessException;
}
----

There are three options to provide or implement a repository:

[source,java]
.Example Spring Data repository
----
public interface SpringDataFooRepository extends FooRepository, Repository<Foo, Integer> {

    @Override
    @Query("SELECT foo FROM Foo ORDER BY foo.name")
    List<Foo> findFoos() throws DataAccessException;
}
----

[source,java]
.Example JPA repository
----
@Repository
public class JpaFooRepositoryImpl implements FooRepository {

    @PersistenceContext
    private EntityManager em;

    @Override
    @SuppressWarnings("unchecked")
    public List<Foo> findFoos() {
        return this.em.createQuery("SELECT foo FROM Foo ORDER BY foo.name").getResultList();
    }
----

[source,java]
.Example JDBC repository
----
@Repository
public class JdbcFooRepositoryImpl implements Repository {

    private NamedParameterJdbcTemplate namedParameterJdbcTemplate;

    @Autowired
    public JdbcRepositoryImpl(DataSource dataSource) {
        this.namedParameterJdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
    }

    @Override
    public List<Foo> findFoos() throws DataAccessException {
        Map<String, Object> params = new HashMap<>();
        return this.namedParameterJdbcTemplate.query(
            "SELECT id, name FROM foo ORDER BY name",
            params,
            BeanPropertyRowMapper.newInstance(Foo.class));
    }
----

[[structure:RepositoryDependencies]]
[source,cypher,role=constraint,requiresConcepts="structure:LayerDependencies"]
.A repository can only have dependencies to other repositories.
----
MATCH
  (type:Spring:Repository)-[:USES]->(otherType:Spring:Component)
WHERE NOT
  otherType:Repository
RETURN DISTINCT
  type as InvalidRepository, otherType as Dependency
----


=== Concepts

[[structure:LayerDependencies]]
[source,cypher,role=concept,requiresConcepts="spring-mvc:Controller,spring-mvc:Service,spring-data:Repository"]
.Creates a USES relation between application layer items, i.e. spring components.
----
MATCH
  (type:Spring:Component)-[:DECLARES]->(:Method)-[:INVOKES]->(:Method)<-[:DECLARES]-(:Type:Interface)<-[:IMPLEMENTS|EXTENDS*]-(otherType:Spring:Component)
WHERE
  type <> otherType
MERGE
  (type)-[:USES]->(otherType)
RETURN
  type as Dependent, collect(distinct otherType.fqn) as Dependencies
----


=== Reports

TIP: GraphML reports may be viewed using http://www.yworks.com/en/products/yfiles/yed/[yEd]. After opening a file you
should apply a layout, e.g. menu:Layout[Hierarchical].


[[structure:LayerDependencies.graphml]]
[source,cypher,role=concept,requiresConcepts="structure:LayerDependencies",reportType="graphml"]
.Actual usage dependencies between the application layers, i.e. controller, service and repository implementations.
----
MATCH
  (type:Spring:Component)-[uses:USES]->(otherType:Spring:Component)
RETURN
  type as Dependent,
  uses as Uses,
  otherType as Dependency
----


[[structure:PackageDependencies.graphml]]
[source,cypher,role=concept,reportType="graphml"]
.Dependencies between packages and their contained types.
----
MATCH
  (package:Package)-[:CONTAINS]->(type:Type)
OPTIONAL MATCH
  (type)-[dependsOn:DEPENDS_ON]->(:Type)
RETURN {
  role : "graph",
  parent : package,
  nodes : collect(type),
  relationships : collect(dependsOn)
} as TypesPerPackage
----
